
spring.application.name=jm-notification

spring.datasource.url=jdbc:postgresql://localhost:5432/job_matrix_local
spring.datasource.username=job_matrix
spring.datasource.password=job_matrix
spring.datasource.driver-class-name =org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size = 10

#spring.profiles.active=local

# AWS Region
cloud.aws.region.static=ap-south-1
#cloud.aws.stack.auto=false

# SQS Listener Configuration
sqs.listener.proposal-submitted-queue.queue-name=testQueue-jm

server.port = 8081